[workspace]
resolver = "3"
members = [
    "crates/deviceinfo",
    "crates/deviceinfo-cli",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "GPL-3.0-or-later"
repository = "https://github.com/shallow-out/devicesinfo"

[workspace.dependencies]
deviceinfo = { path = "crates/deviceinfo" }

clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
lto = "thin"
strip = "symbols"
