[package]
name = "deviceinfo-cli"
description = "deviceinfo 的命令行前端"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "deviceinfo"
path = "src/main.rs"

[dependencies]
deviceinfo.workspace = true

clap.workspace = true
serde_json.workspace = true
